### ISSUE TITLE
MOBProfile: Edit Attribute

### ISSUE THREAD

**Issue by maycon-mello** [SelfKeyFoundation/identity-wallet-mobile#340]

**Comment by rhdelima** [comment]
@maycon-mello Please see issues below:
1. Hard to tap on edit for the last attribute since options overlap with menu
2. When editing attribute, Edit Information is showing Type field instead of the value field
3. When tapping option (3 dots), there is some kind of shadow blocking the wallet
https://drive.google.com/file/d/1vevwgJs-GnwWNKYUtDI8UyZKJK2a0iBu/view?usp=sharing

**Comment by maycon-mello** [comment]
Hi @rhdelima, I've fixed the issues. For the item 3 this is the expected behavior, we should have the shadow when the item is opened https://projects.invisionapp.com/d/?origin=v7#/console/18106826/408184597/preview?scrollOffset=8103. Let me know if you face any other issues.

**Comment by rhdelima** [comment]
Looks good. Pass
